## Project: Weekly Car Sales Analysis

In [1]:
import numpy as np
import pandas as pd

In [27]:
np.random.seed(0)
sales_amounts = np.random.randint(100, size=(6, 5))
sales_amounts

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79]])

In [11]:
# Create Weekly Sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tue", "Wed", "Thur", "Fri", "Sat"],
                            columns = ["Audi", "Honda", "Toyota", "BMW", "Innoson"])
weekly_sales

Audi  Honda  Toyota  BMW  Innoson
Mon     72     46       1   13       41
Tue     93     12      21   94       93
Wed     75      5      27   39       11
Thur    98      3      87   80       46
Fri     90      4      38   71       53
Sat     58     97      18   15       65

In [29]:
# Create the prices array
prices = np.array([150, 132, 95, 149, 119])
prices

array([150, 132,  95, 149, 119])

In [34]:
# Create Car prices DataFrame
car_prices = pd.DataFrame(prices.reshape(1,5),
                         index=["Price (thousand dollars)"],
                         columns = ["Audi", "Honda", "Toyota", "BMW", "Innoson"])
car_prices

Audi  Honda  Toyota  BMW  Innoson
Price (thousand dollars)   150    132      95  149      119

In [35]:
sales_amount

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79]])

In [36]:
prices

array([150, 132,  95, 149, 119])

In [39]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([36840, 30018, 39166, 40489, 39450, 31272])

In [41]:
car_prices

Audi  Honda  Toyota  BMW  Innoson
Price (thousand dollars)   150    132      95  149      119

In [42]:
car_prices.shape, weekly_sales.shape

((1, 5), (6, 5))

In [43]:
daily_sales = car_prices.dot(weekly_sales.T)
daily_sales

Mon    Tue    Wed   Thur    Fri    Sat
Price (thousand dollars)  23783  42602  21595  40755  34524  33184

In [44]:
weekly_sales

Audi  Honda  Toyota  BMW  Innoson
Mon     72     46       1   13       41
Tue     93     12      21   94       93
Wed     75      5      27   39       11
Thur    98      3      87   80       46
Fri     90      4      38   71       53
Sat     58     97      18   15       65

In [45]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Audi  Honda  Toyota  BMW  Innoson  Total ($)
Mon     72     46       1   13       41      23783
Tue     93     12      21   94       93      42602
Wed     75      5      27   39       11      21595
Thur    98      3      87   80       46      40755
Fri     90      4      38   71       53      34524
Sat     58     97      18   15       65      33184

### Questions: Research more on the following
#### 1. `np.random.seed(0)`
#### 2. `daily_sales = car_prices.dot(weekly_sales.T)`