In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
al = np.array([1, 2, 3])
al

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a3 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
al.shape

(3,)

In [6]:
 # Number of dimensions
al.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
al.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [8]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [9]:
sample_array = np.array([ 1,2,3])
sample_array

array([1, 2, 3])

In [10]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
ones.dtype

dtype('float64')

In [12]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [14]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[3, 5, 1, 3, 1],
       [0, 7, 2, 5, 2],
       [7, 3, 9, 8, 1]])

In [15]:
random_array.shape

(3, 5)

In [16]:
random_array.size

15

In [17]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.16761755, 0.07388777, 0.7803349 ],
       [0.33130634, 0.67835312, 0.66098311],
       [0.38027305, 0.76903647, 0.84536398],
       [0.71055665, 0.31423519, 0.97911879],
       [0.83893714, 0.19557563, 0.2425872 ]])

In [18]:
random_array2.size

15

In [19]:
random_array2.shape

(5, 3)

In [20]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.67186013, 0.00389223, 0.79750887],
       [0.77608768, 0.07421795, 0.02860531],
       [0.10391682, 0.97723324, 0.06689922],
       [0.79620527, 0.89210751, 0.01057335],
       [0.14596235, 0.85686565, 0.67275927]])

In [21]:
 # Pseud0-random numbers
np.random.seed(seed=0)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

  ## Viewing arrays and matrices

In [22]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a1

NameError: name 'a1' is not defined

In [ ]:
al

In [ ]:
a2

In [ ]:
a3

In [ ]:
a1[0]

In [ ]:
al[0]

In [ ]:
a3.shape

In [ ]:
a3

In [ ]:
a3[0]

In [ ]:
a2[1]

In [ ]:
a2

In [ ]:
a3

In [ ]:
a3[:2, :2, :2]

In [ ]:
a3[:2, :2]

In [ ]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

In [ ]:
a4.shape, a4.ndim

In [ ]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

In [ ]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]