In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a3 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# al.shape

In [5]:
 # Number of dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [6]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [7]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [8]:
sample_array = np.array([ 1,2,3])
sample_array

array([1, 2, 3])

In [9]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ones.dtype

dtype('float64')

In [11]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [13]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[4, 4, 2, 6, 8],
       [7, 0, 2, 3, 0],
       [9, 3, 7, 0, 1]])

In [14]:
random_array.shape

(3, 5)

In [15]:
random_array.size

15

In [16]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.14845799, 0.15212612, 0.93111802],
       [0.22326343, 0.05286374, 0.27365935],
       [0.93040611, 0.18897059, 0.01232836],
       [0.74676929, 0.26540664, 0.22456912],
       [0.74463949, 0.8244884 , 0.49295171]])

In [17]:
random_array2.size

15

In [18]:
random_array2.shape

(5, 3)

In [19]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.48259673, 0.72336071, 0.45636122],
       [0.36919725, 0.6898743 , 0.69860695],
       [0.97368124, 0.78141181, 0.01535939],
       [0.95845608, 0.84590577, 0.37936999],
       [0.72820996, 0.64288653, 0.84222506]])

In [20]:
 # Pseud0-random numbers
np.random.seed(seed=0)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

  ## Viewing arrays and matrices

In [21]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a1

array([1, 2, 3])

In [23]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [24]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
a1[0]

1

In [26]:
a1[0]

1

In [27]:
a3.shape

(2, 3, 3)

In [28]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [29]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a2[1]

array([4. , 5. , 6.5])

In [31]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [34]:
a3[:2, :2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [35]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [36]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [37]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]],


       [[[6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1]],

        [[1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5]]]])

In [38]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :3]

array([[[[8, 8, 2],
         [0, 8, 8],
         [2, 8, 4],
         [4, 3, 6]],

        [[0, 8, 5],
         [9, 6, 5],
         [8, 0, 4],
         [5, 7, 8]],

        [[2, 8, 6],
         [1, 6, 8],
         [2, 3, 6],
         [5, 7, 0]]],


       [[[6, 5, 8],
         [9, 7, 5],
         [5, 3, 3],
         [9, 9, 7]],

        [[3, 9, 7],
         [1, 2, 2],
         [5, 8, 4],
         [5, 5, 0]],

        [[1, 0, 3],
         [4, 4, 0],
         [7, 3, 2],
         [2, 1, 4]]]])

## Manipulating and Comapring arrays

### Arithmetic

In [39]:
a1

array([1, 2, 3])

In [40]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [41]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [42]:
a1 + ones

array([2., 3., 4.])

In [43]:
a1 - ones

array([0., 1., 2.])

In [44]:
a1 * ones

array([1., 2., 3.])

In [45]:
a1

array([1, 2, 3])

In [46]:
a1 * ones

array([1., 2., 3.])

In [47]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [48]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [49]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [50]:
a1

array([1, 2, 3])

In [51]:
a1

array([1, 2, 3])

In [52]:
a1

array([1, 2, 3])

In [53]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2

In [ ]:
a3

In [ ]:
a3 * a2

In [ ]:
a1 / 1

In [ ]:
a2 / a1

In [ ]:
# Floor division: It removes the decimals (rounds down)
a2 // a1

In [ ]:
a2 ** 2 # raised to the power of 2

In [ ]:
np.square(a2) # Numpy's saquare function

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
np.exp(a1) # exponential

In [ ]:
a1

In [ ]:
np.log(a1)

### Aggregation
#### Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
np.sum(a1)

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [ ]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
# %timeit(it calculates how long it takes a particular line of code to run)
%timeit sum(massive_array) # Python's sum
%timeit np.sum(massive_array) # NumPy's sum

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)


In [ ]:
np.min(a2)

In [ ]:
# Variance
np.var(a2)

In [ ]:
# Standard deviation
np.std(a2)

In [ ]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = ([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

### Reshaping and transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2

In [ ]:
a2.reshape(2, 3, 1)

In [ ]:
a2.reshape(2, 3, 1).shape

In [ ]:
a3.shape

In [ ]:
a2

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

In [ ]:
a3

In [ ]:
a2_reshape * a3

In [ ]:
a2

In [ ]:
# Transpose
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

  ## Dot Product

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot Product
np.dot(mat1, mat2)

In [ ]:
mat1.T

In [ ]:
mat1.T.shape

In [ ]:
mat2.T

In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

## Comparison Operators

In [ ]:
a1

In [ ]:
al

In [ ]:
a1

In [ ]:
 a2

In [ ]:
a1 > a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
a1 == a2

## Sorting arrays

In [ ]:
random_array = np.random.randint(10, size=(3,5))
random_array

In [ ]:
random_array.shape

In [ ]:
np.sort(random_array)

In [ ]:
random_array

In [ ]:
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [ ]:
random_array

In [ ]:
np.argmax(random_array, axis=0)

In [ ]:
np.argmax(random_array, axis=1)