In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
al = np.array([1, 2, 3])
al

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a3 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
al.shape

(3,)

In [6]:
 # Number of dimensions
al.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
al.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [8]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


## Creating arrays

In [9]:
sample_array = np.array([ 1,2,3])
sample_array

array([1, 2, 3])

In [10]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
ones.dtype

dtype('float64')

In [12]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [14]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[0, 8, 9, 4, 2],
       [6, 1, 8, 7, 6],
       [7, 6, 3, 5, 5]])

In [15]:
random_array.shape

(3, 5)

In [16]:
random_array.size

15

In [17]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.55170813, 0.00148975, 0.00573213],
       [0.81409816, 0.14089468, 0.47759794],
       [0.57807252, 0.82030425, 0.02775245],
       [0.6973614 , 0.65224079, 0.91418047],
       [0.96673183, 0.7833665 , 0.49210076]])

In [18]:
random_array2.size

15

In [19]:
random_array2.shape

(5, 3)

In [20]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.84774971, 0.08855711, 0.59597402],
       [0.25348799, 0.66620896, 0.71452754],
       [0.01914188, 0.05017492, 0.14912214],
       [0.68873712, 0.44361343, 0.50243573],
       [0.92260082, 0.25057587, 0.40227163]])

In [21]:
 # Pseud0-random numbers
np.random.seed(seed=0)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

  ## Viewing arrays and matrices

In [22]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a1

NameError: name 'a1' is not defined

In [24]:
al

array([1, 2, 3])

In [25]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a1[0]

NameError: name 'a1' is not defined

In [28]:
al[0]

1

In [29]:
a3.shape

(2, 3, 3)

In [30]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a2[1]

array([4. , 5. , 6.5])

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [36]:
a3[:2, :2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [38]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]],


       [[[6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1]],

        [[1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5]]]])

In [39]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [43]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[8, 9, 4, 1, 5],
         [0, 3, 6, 3, 0],
         [3, 6, 9, 5, 1],
         [7, 3, 4, 7, 0]],

        [[3, 5, 6, 6, 7],
         [4, 7, 2, 0, 1],
         [6, 5, 9, 4, 8],
         [7, 8, 6, 1, 4]],

        [[8, 5, 1, 6, 2],
         [7, 5, 7, 9, 6],
         [6, 3, 9, 9, 3],
         [4, 4, 1, 3, 9]]],


       [[[5, 1, 9, 7, 5],
         [4, 2, 0, 8, 7],
         [1, 1, 1, 9, 7],
         [4, 8, 6, 1, 2]],

        [[8, 4, 7, 9, 8],
         [8, 3, 2, 5, 6],
         [4, 5, 7, 9, 0],
         [3, 5, 5, 7, 8]],

        [[0, 2, 6, 5, 1],
         [5, 1, 9, 2, 3],
         [0, 3, 0, 1, 2],
         [2, 3, 4, 5, 8]]]])

In [49]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[8, 9, 4, 1],
         [0, 3, 6, 3],
         [3, 6, 9, 5],
         [7, 3, 4, 7]],

        [[3, 5, 6, 6],
         [4, 7, 2, 0],
         [6, 5, 9, 4],
         [7, 8, 6, 1]],

        [[8, 5, 1, 6],
         [7, 5, 7, 9],
         [6, 3, 9, 9],
         [4, 4, 1, 3]]],


       [[[5, 1, 9, 7],
         [4, 2, 0, 8],
         [1, 1, 1, 9],
         [4, 8, 6, 1]],

        [[8, 4, 7, 9],
         [8, 3, 2, 5],
         [4, 5, 7, 9],
         [3, 5, 5, 7]],

        [[0, 2, 6, 5],
         [5, 1, 9, 2],
         [0, 3, 0, 1],
         [2, 3, 4, 5]]]])