## Dot product example (nut butter sales)

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [3]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, 
                            index=["Mon", "Tues", "Wed", "Thur", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [4]:
# Create the prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [5]:
prices.shape

(3,)

In [6]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"], 
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [7]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [8]:
prices

array([10,  8, 12])

In [9]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [10]:
#Create daily_sales
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [11]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [12]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thur  Fri
Price  240   138  458   232  142

In [13]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [14]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon              12             15              0        240
Tues              3              3              7        138
Wed               9             19             18        458
Thur              4              6             12        232
Fri               1              6              7        142