## **Applied Assignment 1**

**1.** Define Natural Language Processing (NLP) in your own words:

**Answer:**  
Natural Language Processing (NLP) refers to the branch of artificial intelligence (AI) that involves the ability of computers to read, understand, interpret, and generate human languages in a meaningful way.

2. List at least three real-world applications of NLP and explain their significance:
**Answers:**  
Sentiment Analysis: Used to analyze the sentiment expressed in social media posts, customer feedback, or reviews, helping businesses understand customer opinions.

Chatbots and Virtual Assistants: NLP powers virtual assistants like Siri and Alexa to understand and respond to user queries, providing convenience and improving customer service.

Machine Translation: NLP enables the translation of text from one language to another, facilitating communication across language barriers in real-time applications like Google Translate.

3. Identify and explain two challenges that make NLP complex:
**Answers:**

Ambiguity: Words can have multiple meanings depending on the context, making it difficult for computers to determine the correct meaning.

Context Understanding: NLP systems often struggle with understanding context, such as slang, idiomatic expressions, or nuances in conversation, which are crucial for accurate interpretation and response

4. Extract the following patterns using regex:  
a) All email addresses from the text below:  
"Contact us at support@company.com or sales@business.org.
For more, email info@service.net."  
b) All words that end with "ing" from this sentence:  
"NLP is amazing for cleaning and processing text while learning new techniques."

In [1]:
import re
text = "Contact us at support@company.com or sales@business.org. For more, email info@service.net"
emails = re.findall(r'\b[\w.-]+@[\w.-]+\.\w+\b', text)
print("Emails are: ", emails)

Emails are:  ['support@company.com', 'sales@business.org', 'info@service.net']


In [2]:
import re
text = "NLP is amazing for cleaning and processing text while learning new techniques."
words = re.findall(r'\b\w+ing\b', text)
print("Words ending in 'ing' are: ", words)

Words ending in 'ing' are:  ['amazing', 'cleaning', 'processing', 'learning']


5. Write a Python program to clean the following text by:  
a) Removing all punctuation.  
b) Converting it to lowercase.  
c) Splitting it into words.

In [3]:
import re
text = "Contact us at support@company.com or sales@business.org. For more, email info@service.net"
cleaned = re.sub(r'[^a-z0-9A-Z\s]', '', text)
print(cleaned)

Contact us at supportcompanycom or salesbusinessorg For more email infoservicenet


In [4]:
text = "Contact us at support@company.com or sales@business.org. For more, email info@service.net"
lower_cased = text.lower()
print(lower_cased)

contact us at support@company.com or sales@business.org. for more, email info@service.net


In [5]:
text = "Contact us at support@company.com or sales@business.org. For more, email info@service.net"
splited = text.split()
print(splited)

['Contact', 'us', 'at', 'support@company.com', 'or', 'sales@business.org.', 'For', 'more,', 'email', 'info@service.net']


## **Applied Assignment 2**

1. Apply text cleaning techniques to preprocess the following text:"  
"OMG!! NLP is soooo cool 🤩...!!! It costs $1000. Learn it now at https://3mtt.com 😎.

**Answer:**

The following are applied:

a. use lowercase to convert all text to same case.  
b. remove irrelevant punctuation marks and symbols.  
c. eliminate stopwords.  
d. remove numbers from it.

**Output:** nlp is so cool learn it.

2. Perform both word-level and sentence-level tokenization on the given text.


"Tokenization is the first step in NLP. It splits text into smaller pieces for analysis."

Use NLTK to perform word tokenization.

Use NLTK to perform sentence tokenization

**Answers:**

In [6]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [7]:
# word tokenization
import nltk
text = "Tokenization is the first step in NLP. It splits text into smaller pieces for analysis."
word = nltk.word_tokenize(text)
print(f"Tokenized words: {word}")

Tokenized words: ['Tokenization', 'is', 'the', 'first', 'step', 'in', 'NLP', '.', 'It', 'splits', 'text', 'into', 'smaller', 'pieces', 'for', 'analysis', '.']


In [8]:
# sentence tokenization
text = "Tokenization is the first step in NLP. It splits text into smaller pieces for analysis."
sentence = nltk.sent_tokenize(text)
print(f"Tokenized sentences: {sentence}")

Tokenized sentences: ['Tokenization is the first step in NLP.', 'It splits text into smaller pieces for analysis.']


3. Apply stemming and lemmatization techniques to a list of words:
["running", "flies", "studies", "easily", "studying", "better"]

Use Porter Stemmer to perform stemming on the words.

Use spaCy to perform lemmatization on the same words.


**Answers:**

In [9]:
# Using PorterStemmer

from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
words = ["running", "flies", "studies", "easily", "studying", "better"]
stemmed_words = [stemmer.stem(word) for word in words]
print(f"Stemmed words: {stemmed_words}")

Stemmed words: ['run', 'fli', 'studi', 'easili', 'studi', 'better']


In [10]:
# Lemmatization with spaCy
import spacy
nlp = spacy.load('en_core_web_sm')
words = ["running", "flies", "studies", "easily", "studying", "better"]
lemmatized_words = [nlp(word)[0].lemma_ for word in words]
print(f"Lemmatized words: {lemmatized_words}")

Lemmatized words: ['run', 'fly', 'study', 'easily', 'study', 'well']


## **Applied Assignment 3**

1. Define a vocabulary of at least 5 unique words. Write Python code to generate one-hot encoded vectors for your vocabulary.

**Answer:**

In [11]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

vocabulary = ["ship", "airplane","car", "bicycle", "helocopter"]
num_ind = np.array(vocabulary).reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False)
one_hot = encoder.fit_transform(num_ind)

print("Vocabulary:", vocabulary)
print("One Hot Encoded Vectors:\n", one_hot)

Vocabulary: ['ship', 'airplane', 'car', 'bicycle', 'helocopter']
One Hot Encoded Vectors:
 [[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


2. Use the following sentences as your dataset:
* "The quick brown fox jumps over the lazy dog."
* "The dog sleeps in the kennel"

-Write Python code to generate a Bag of Words representation for the dataset using CountVectorizer.


-Write Python code to compute the TF-IDF representation using TfidfVectorizer.

**Answers:**

In [12]:
# Bag of words using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

sentences = ["The quick brown fox jumps over the lazy dog.", "The dog sleeps in the kennel"]
vectorizer = CountVectorizer()
bagOfwords = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Bag of Words Representation:\n", bagOfwords.toarray())

Vocabulary: ['brown' 'dog' 'fox' 'in' 'jumps' 'kennel' 'lazy' 'over' 'quick' 'sleeps'
 'the']
Bag of Words Representation:
 [[1 1 1 0 1 0 1 1 1 0 2]
 [0 1 0 1 0 1 0 0 0 1 2]]


In [13]:
# TF-IDF using TfidfVectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

sentences = ["The quick brown fox jumps over the lazy dog.", "The dog sleeps in the kennel"]
tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(sentences)

print("Vocabulary:", tfidf_vectorizer.get_feature_names_out())
print("TF-IDF Representation:\n", tfidf.toarray())

Vocabulary: ['brown' 'dog' 'fox' 'in' 'jumps' 'kennel' 'lazy' 'over' 'quick' 'sleeps'
 'the']
TF-IDF Representation:
 [[0.342369   0.24359836 0.342369   0.         0.342369   0.
  0.342369   0.342369   0.342369   0.         0.48719673]
 [0.         0.30253071 0.         0.42519636 0.         0.42519636
  0.         0.         0.         0.42519636 0.60506143]]


3. Create a small dataset of at least 3 sentences related to animals.

Example: "The cat meows. The dog barks. The bird sings."

* Write Python code to:
     * Train a Word2Vec model using gensim.
     * Retrieve the vector embedding for the word "dog".


**Answers:**

In [14]:

!pip uninstall -y scipy gensim
!pip install scipy==1.10.1
!pip install gensim==4.3.2

Found existing installation: scipy 1.10.1
Uninstalling scipy-1.10.1:
  Successfully uninstalled scipy-1.10.1
Found existing installation: gensim 4.3.2
Uninstalling gensim-4.3.2:
  Successfully uninstalled gensim-4.3.2
  Using cached scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
Using cached scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.1 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jaxlib 0.5.1 requires scipy>=1.11.1, but you have scipy 1.10.1 which is incompatible.
jax 0.5.2 requires scipy>=1.11.1, but you have scipy 1.10.1 which is incompatible.
cvxpy 1.6.4 requires scipy>=1.11.0, but you have scipy 1.10.1 which is incompatible.
scikit-image 0.25.2 requires scipy>=1.11.4, but you have scipy 1.10.1 which is incompatible.
  Using cached gensim-4.3.2-cp311-cp311-manylinux_2_17_x86_64

In [15]:
from gensim.models import Word2Vec

sentences = [["the", "dog", "barks"], ["the", "owl", "hoots"], ["the", "snake", "hisses"]]
word2vec_model = Word2Vec(sentences, vector_size=10, window=2, min_count=1, workers=4)
print("Word Embedding for 'dog':\n", word2vec_model.wv['dog'])

Word Embedding for 'dog':
 [-0.01577653  0.00321372 -0.0414063  -0.07682689 -0.01508008  0.02469795
 -0.00888027  0.05533662 -0.02742977  0.02260065]


4. Load the pretrained Glove model (glove-wiki-gigaword-50) using gensim.

  * Write Python code to:
       * Retrieve the embedding for the word "king".
       * Find the 5 most similar words to "king".


**Answer:**

In [16]:
import gensim.downloader as api

glove_model = api.load("glove-wiki-gigaword-50")

print("Word Embedding for 'king':\n", glove_model['king'])

print("Words similar to 'king':\n", glove_model.most_similar('king', topn=5))


Word Embedding for 'king':
 [ 0.50451   0.68607  -0.59517  -0.022801  0.60046  -0.13498  -0.08813
  0.47377  -0.61798  -0.31012  -0.076666  1.493    -0.034189 -0.98173
  0.68229   0.81722  -0.51874  -0.31503  -0.55809   0.66421   0.1961
 -0.13495  -0.11476  -0.30344   0.41177  -2.223    -1.0756   -1.0783
 -0.34354   0.33505   1.9927   -0.04234  -0.64319   0.71125   0.49159
  0.16754   0.34344  -0.25663  -0.8523    0.1661    0.40102   1.1685
 -1.0137   -0.21585  -0.15155   0.78321  -0.91241  -1.6106   -0.64426
 -0.51042 ]
Words similar to 'king':
 [('prince', 0.8236179351806641), ('queen', 0.7839043140411377), ('ii', 0.7746230363845825), ('emperor', 0.7736247777938843), ('son', 0.766719400882721)]
